### ISSUE TITLE
数据与模型

### ISSUE THREAD

**Issue by h1063135843** [Geralt-of-winterfall/cube_slam#1]
能提供一下整理好的数据范例吗，还有yolov5的Onnx检测模型，缺这些没办法跑起来。好人一生平安。

**Comment by Geralt-of-winterfall** [comment]
你好，数据范例是指什么？yolov5的Onnx检测模型我用的是官方的模型，体积较大，传GitHub不方便，可以直接去官方项目主页进行下载。

**Comment by h1063135843** [comment]
> 你好，数据范例是指什么？yolov5的Onnx检测模型我用的是官方的模型，体积较大，传GitHub不方便，可以直接去官方项目主页进行下载。

就是scene folder那个文件夹，我从cubeslam official repo上下载的数据长得好像和这里用的不太一样。感谢指导，我去下载一下检测模型

**Comment by Geralt-of-winterfall** [comment]
> > 你好，数据范例是指什么？yolov5的Onnx检测模型我用的是官方的模型，体积较大，传GitHub不方便，可以直接去官方项目主页进行下载。
> 
> 就是scene folder那个文件夹，我从cubeslam official repo上下载的数据长得好像和这里用的不太一样。感谢指导，我去下载一下检测模型

我修改的版本实现了在线检测，只需要给定yolo模型和数据集序列，就可以按cube slam的方法进行3D Object检测。只需要按`./cube_slam /home/user_name/KITTI/dataset/sequences/07 ../data_folder/ ../data/ORBvoc.bin ../data/KITTI_mono.yaml`给定参数即可，数据集使用下载的KITTI，不需要修改。

**Comment by h1063135843** [comment]
> > > 你好，数据范例是指什么？yolov5的Onnx检测模型我用的是官方的模型，体积较大，传GitHub不方便，可以直接去官方项目主页进行下载。
> > 
> > 
> > 就是scene folder那个文件夹，我从cubeslam official repo上下载的数据长得好像和这里用的不太一样。感谢指导，我去下载一下检测模型
> 
> 我修改的版本实现了在线检测，只需要给定yolo模型和数据集序列，就可以按cube slam的方法进行3D Object检测。只需要按`./cube_slam /home/user_name/KITTI/dataset/sequences/07 ../data_folder/ ../data/ORBvoc.bin ../data/KITTI_mono.yaml`给定参数即可，数据集使用下载的KITTI，不需要修改。

非常感谢，已经跑通了。
